### ISSUE TITLE
Falla grave en la actividad "¡A la ducha!"

### ISSUE THREAD

**Issue by milmazz** [milmazz/pygame-salud#1]
Al entrar en la actividad llamada **¡A la ducha!** y solamente dar clic al botón izquierdo de ratón se cierra la aplicación. El _traceback_ obtenido es el siguiente:

```
$ python salud.py
Traceback (most recent call last):
  File "salud.py", line 42, in <module>
    if __name__ == '__main__': main()
  File "salud.py", line 40, in main
    MenuActivity(screen, items).run()
  File "/home/mmazzarri/Trabajo/cenamec/pygame-salud/src/activity.py", line 42, in run 
    self.on_change()
  File "/home/mmazzarri/Trabajo/cenamec/pygame-salud/src/menu.py", line 81, in on_change
    x.run(self.screen)
  File "/home/mmazzarri/Trabajo/cenamec/pygame-salud/src/menu.py", line 22, in run 
    self.activity(screen).run()
  File "/home/mmazzarri/Trabajo/cenamec/pygame-salud/src/activity.py", line 37, in run 
    self.handle_events()
  File "/home/mmazzarri/Trabajo/cenamec/pygame-salud/src/links.py", line 92, in handle_events
    self.validate_selection()
  File "/home/mmazzarri/Trabajo/cenamec/pygame-salud/src/links.py", line 105, in validate_selection
    selection = self.selection
```

**Comment by lmolina** [comment]
La se reestructuro, la nueva clase no presenta este error
